@echo off
mkdir src\main\services
mkdir src\main\utils
mkdir src\renderer\components\Notification
mkdir src\renderer\components\Modal
mkdir src\renderer\components\FilePicker
mkdir src\renderer\components\GradientEditor
mkdir src\renderer\components\Countdown
mkdir src\renderer\components\TabSwitcher
mkdir src\renderer\services\IpcRendererService
mkdir src\renderer\services\WebcamService
mkdir src\renderer\services\CanonCameraService
mkdir src\renderer\services\LocalizationService
mkdir src\renderer\services\ThemeService
mkdir src\renderer\assets\css
mkdir src\renderer\assets\fonts
mkdir src\renderer\assets\icons
mkdir src\renderer\utils
mkdir src\shared\constants
mkdir src\shared\utils
mkdir src\windows\launcher
mkdir src\windows\configurator
mkdir src\windows\photobooth